SELECT 
    R.FOOD_TYPE, 
    R.REST_ID, 
    R.REST_NAME, 
    R.FAVORITES
FROM REST_INFO R
INNER JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS MAX_FAVORITES ON R.FOOD_TYPE = MAX_FAVORITES.FOOD_TYPE AND R.FAVORITES = MAX_FAVORITES.FAVORITES
ORDER BY R.FOOD_TYPE DESC;

